# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI

on  :
  push        :
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps  :
      - uses: actions/checkout@v2
      - name: Run script file
        run: pwd && ls
        shell: bash
       
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push docker image
        with:
          image   : jsr1der/first-angular-docker
          tags    : v1.0.0
          dockerfile: ./first-angular-docker/Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v3
      - name: deploy
        if : github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X GET "$deploy_url"
